// packages/providers/frameworks/solid/src/index.ts
import { createSignal, onCleanup, onMount, type Accessor } from "solid-js";
import { createDocumentProjection } from "@automerge/automerge-repo-solid-primitives";
import type { Doc, DocHandle } from "@automerge/automerge-repo";
import * as Providers from "@inkandswitch/patchwork-providers";
import type { EventArgs } from "@inkandswitch/patchwork-providers";

/**
 * Generic reactive request. Dispatches a `patchwork:request` of `type` on
 * mount and returns an accessor that updates when the provider responds.
 * `T` is the actual response type (e.g. `Repo`, plain data, a `DocHandle`).
 *
 * For request types that return a `DocHandle<T>` and a reactive doc
 * projection is wanted, prefer `requestDoc` instead.
 */
export function request<T>(
  element: HTMLElement,
  type: string,
  args?: Record<string, unknown>
): Accessor<T | undefined> {
  const [value, setValue] = createSignal<T | undefined>(undefined);
  onMount(() => {
    Providers.request<T>(element, type, args).then((v) => {
      if (v == null) return;
      // Wrap in a thunk so Solid does not treat values with call-like
      // methods (e.g. DocHandle, Repo) as setter functions.
      setValue(() => v);
    });
  });
  return value;
}

/**
 * Handle-specialized request. Use when the responding provider returns a
 * `DocHandle<T>`. Returns `[doc, handle]` matching the shape of
 * solid-primitives' `useDocument`. Both are accessors; they read `undefined`
 * until the provider responds. `T` is the doc shape inside the handle.
 */
export function requestDoc<T extends object>(
  element: HTMLElement,
  type: string,
  args?: Record<string, unknown>
): [Accessor<Doc<T> | undefined>, Accessor<DocHandle<T> | undefined>] {
  const handle = request<DocHandle<T>>(element, type, args);
  const doc = createDocumentProjection<T>(handle);
  return [doc, handle];
}

/**
 * Generic reactive subscription. Opens a `patchwork:subscribe` of `type` on
 * mount and returns an accessor that updates on every value the provider
 * pushes. The subscription is torn down on cleanup. `T` is the streamed value
 * type (e.g. plain data, a `DocHandle`).
 */
export function subscribe<T>(
  element: HTMLElement,
  type: string,
  args?: EventArgs
): Accessor<T | undefined> {
  const [value, setValue] = createSignal<T | undefined>(undefined);
  onMount(() => {
    const unsubscribe = Providers.subscribe<T>(element, type, args ?? {}, (v) => {
      if (v == null) return;
      // Wrap in a thunk so Solid does not treat values with call-like
      // methods (e.g. DocHandle, Repo) as setter functions.
      setValue(() => v);
    });
    onCleanup(unsubscribe);
  });
  return value;
}

// packages/providers/frameworks/react/src/index.ts
import { useEffect, useState } from "react";
import { useDocument } from "@automerge/automerge-repo-react-hooks";
import type { Doc, DocHandle } from "@automerge/automerge-repo";
import * as Providers from "@inkandswitch/patchwork-providers";

/**
 * Generic reactive request hook. Dispatches a `patchwork:request` of `type`
 * on mount (and whenever `element`/`type` change) and returns the response
 * once the provider answers. `T` is the actual response type (e.g. `Repo`,
 * plain data, a `DocHandle`).
 *
 * For request types that return a `DocHandle<T>` and a live doc is wanted,
 * prefer `useDocRequest` instead.
 */
export function useRequest<T>(
  element: HTMLElement,
  type: string,
  args?: Record<string, unknown>
): T | undefined {
  const [value, setValue] = useState<T | undefined>(undefined);

  useEffect(() => {
    let canceled = false;
    Providers.request<T>(element, type, args).then((v) => {
      if (canceled || v == null) return;
      setValue(() => v);
    });
    return () => {
      canceled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [element, type]);

  return value;
}

/**
 * Handle-specialized request hook. Use when the responding provider returns
 * a `DocHandle<T>`. Returns `[doc, handle]` matching the shape of
 * `useDocument` from `@automerge/automerge-repo-react-hooks`. `T` is the doc
 * shape inside the handle.
 */
export function useDocRequest<T>(
  element: HTMLElement,
  type: string,
  args?: Record<string, unknown>
): [Doc<T> | undefined, DocHandle<T> | undefined] {
  const handle = useRequest<DocHandle<T>>(element, type, args);
  const [doc] = useDocument<T>(handle?.url);
  return [doc, handle];
}
